### ISSUE TITLE
Requirements are a bit too strict

### ISSUE THREAD

**Issue by EiffL** [marius311/muse_inference#2]
Unfortunately some of us are still stuck in the past....

https://github.com/marius311/muse_inference/blob/bbdba8a4b9e173f0a6f576597895c132d4c7d597/pyproject.toml#L8

exludes python 3.8 which seems a bit too drastic.

**Comment by EiffL** [comment]
Case and point:
https://colab.research.google.com/drive/130eWK3SrOwwxVQVxt-eZULZnm3fMQtc8?usp=sharing
![image](https://user-images.githubusercontent.com/861591/150407496-c3990d7e-b258-4a3f-9222-91467fc94cfa.png)

**Comment by marius311** [comment]
Thanks for flagging, I relaxed the requirements a bit. Just tested and its installable on Collab now.
